server:
  port: 8080
mybatis:
  config-location: classpath:mybatis-config.xml
spring:
  thymeleaf:
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
  datasource:
    name: datasource
    url: jdbc:mysql://localhost:3306/infomanager?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat, wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true